// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckAdminPrivileges():Promise<boolean>;

export function CreateService(arg1:main.ServiceConfig):Promise<main.Service>;

export function DeleteService(arg1:string):Promise<void>;

export function GetAutoStartStatus():Promise<boolean>;

export function GetServiceAutoStart(arg1:string):Promise<boolean>;

export function GetServices():Promise<Array<main.Service>>;

export function HideWindow():Promise<void>;

export function RestartAsAdmin():Promise<void>;

export function SelectDirectory():Promise<string>;

export function SelectFile():Promise<string>;

export function SetAutoStart(arg1:boolean):Promise<void>;

export function SetServiceAutoStart(arg1:string,arg2:boolean):Promise<void>;

export function ShowWindow():Promise<void>;

export function StartService(arg1:string):Promise<void>;

export function StopService(arg1:string):Promise<void>;
