// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAdminPrivileges() {
  return window['go']['main']['App']['CheckAdminPrivileges']();
}

export function CreateService(arg1) {
  return window['go']['main']['App']['CreateService'](arg1);
}

export function DeleteService(arg1) {
  return window['go']['main']['App']['DeleteService'](arg1);
}

export function GetAutoStartStatus() {
  return window['go']['main']['App']['GetAutoStartStatus']();
}

export function GetServiceAutoStart(arg1) {
  return window['go']['main']['App']['GetServiceAutoStart'](arg1);
}

export function GetServices() {
  return window['go']['main']['App']['GetServices']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function RestartAsAdmin() {
  return window['go']['main']['App']['RestartAsAdmin']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SetAutoStart(arg1) {
  return window['go']['main']['App']['SetAutoStart'](arg1);
}

export function SetServiceAutoStart(arg1, arg2) {
  return window['go']['main']['App']['SetServiceAutoStart'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartService(arg1) {
  return window['go']['main']['App']['StartService'](arg1);
}

export function StopService(arg1) {
  return window['go']['main']['App']['StopService'](arg1);
}
